# Generated by Django 5.2.16 on 2026-07-21 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_portal", "0001_initial"),
        ("orders", "0005_companyimportbatch_companyimportitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerportalaccess",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_portal_accesses_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="criado por",
            ),
        ),
        migrations.AddField(
            model_name="customerportalaccess",
            name="revocation_reason",
            field=models.CharField(blank=True, max_length=300, verbose_name="motivo do bloqueio"),
        ),
        migrations.AddField(
            model_name="customerportalaccess",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="bloqueado em"),
        ),
        migrations.AddField(
            model_name="customerportalaccess",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_portal_accesses_revoked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="bloqueado por",
            ),
        ),
        migrations.CreateModel(
            name="CustomerPortalAccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=180, verbose_name="empresa ou cliente informado"),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[("individual", "Pessoa física"), ("company", "Pessoa jurídica")],
                        max_length=20,
                        verbose_name="natureza",
                    ),
                ),
                ("document_fingerprint", models.CharField(editable=False, max_length=64)),
                (
                    "document_last_four",
                    models.CharField(
                        editable=False, max_length=4, verbose_name="final do documento"
                    ),
                ),
                ("requester_name", models.CharField(max_length=150, verbose_name="solicitante")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                ("phone", models.CharField(max_length=30, verbose_name="telefone")),
                ("message", models.CharField(blank=True, max_length=1000, verbose_name="mensagem")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_review", "Em análise"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="solicitada em"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="analisada em"),
                ),
                (
                    "decision_notes",
                    models.CharField(blank=True, max_length=1000, verbose_name="decisão interna"),
                ),
                ("idempotency_fingerprint", models.CharField(editable=False, max_length=64)),
                ("abuse_metadata", models.JSONField(blank=True, default=dict, editable=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portal_access_requests",
                        to="orders.company",
                        verbose_name="empresa vinculada",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_access_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsável pela análise",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitação de acesso ao portal",
                "verbose_name_plural": "solicitações de acesso ao portal",
                "ordering": ("-requested_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"], name="portal_access_req_status_idx"
                    ),
                    models.Index(
                        fields=["idempotency_fingerprint", "requested_at"],
                        name="portal_access_req_idem_idx",
                    ),
                ],
            },
        ),
    ]
