# Generated by Django 5.2.16 on 2026-07-18 05:40

import django.db.models.deletion
import django.utils.timezone
import orders.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(default=orders.models.company_code, editable=False, max_length=20, unique=True)),
                ("name", models.CharField(max_length=180, verbose_name="empresa")),
                ("responsible_name", models.CharField(blank=True, max_length=150, verbose_name="responsável")),
                ("phone", models.CharField(blank=True, max_length=30, verbose_name="telefone")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="endereço")),
                ("city", models.CharField(blank=True, max_length=120, verbose_name="cidade")),
                ("customer_type", models.CharField(choices=[("monthly", "Mensalista"), ("spot", "Avulso")], default="spot", max_length=20, verbose_name="tipo de cliente")),
                ("payment_terms", models.CharField(blank=True, max_length=180, verbose_name="forma/condição de pagamento")),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                ("active", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ("name",),
                "indexes": [models.Index(fields=["active", "name"], name="orders_comp_active_fdb946_idx")],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(default=orders.models.order_number, editable=False, max_length=20, unique=True)),
                ("order_date", models.DateField(default=django.utils.timezone.localdate, verbose_name="data do pedido")),
                ("delivery_date", models.DateField(verbose_name="data da entrega")),
                ("delivery_time", models.TimeField(blank=True, null=True, verbose_name="horário da entrega")),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("received", "Recebido"), ("in_production", "Em produção"), ("out_for_delivery", "Saiu para entrega"), ("delivered", "Entregue"), ("cancelled", "Cancelado")], default="pending", max_length=30, verbose_name="status")),
                ("delivery_location", models.CharField(blank=True, max_length=255, verbose_name="local da entrega")),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=14, verbose_name="valor total")),
                ("delivered_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="entregue em")),
                ("cancelled_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="cancelado em")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="orders.company", verbose_name="empresa")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders_created", to=settings.AUTH_USER_MODEL, verbose_name="criado por")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders_updated", to=settings.AUTH_USER_MODEL, verbose_name="atualizado por")),
            ],
            options={
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
                "ordering": ("-delivery_date", "-delivery_time", "number"),
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("from_status", models.CharField(choices=[("pending", "Pendente"), ("received", "Recebido"), ("in_production", "Em produção"), ("out_for_delivery", "Saiu para entrega"), ("delivered", "Entregue"), ("cancelled", "Cancelado")], max_length=30, verbose_name="status anterior")),
                ("to_status", models.CharField(choices=[("pending", "Pendente"), ("received", "Recebido"), ("in_production", "Em produção"), ("out_for_delivery", "Saiu para entrega"), ("delivered", "Entregue"), ("cancelled", "Cancelado")], max_length=30, verbose_name="novo status")),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="motivo")),
                ("changed_at", models.DateTimeField(auto_now_add=True, verbose_name="alterado em")),
                ("idempotency_key", models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="chave de idempotência")),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_status_changes", to=settings.AUTH_USER_MODEL, verbose_name="alterado por")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="orders.order", verbose_name="pedido")),
            ],
            options={
                "verbose_name": "histórico de status",
                "verbose_name_plural": "históricos de status",
                "ordering": ("-changed_at",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(default=orders.models.product_code, editable=False, max_length=20, unique=True)),
                ("name", models.CharField(max_length=180, verbose_name="produto")),
                ("category", models.CharField(blank=True, max_length=100, verbose_name="categoria")),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="valor unitário")),
                ("active", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ("name",),
                "indexes": [models.Index(fields=["active", "name"], name="orders_prod_active_eec462_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(("unit_price__gte", 0)), name="product_unit_price_non_negative")],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_name", models.CharField(editable=False, max_length=180, verbose_name="descrição congelada")),
                ("quantity", models.PositiveIntegerField(verbose_name="quantidade")),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="valor unitário")),
                ("line_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=14, verbose_name="valor total do item")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.order", verbose_name="pedido")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="order_items", to="orders.product", verbose_name="produto")),
            ],
            options={
                "verbose_name": "item do pedido",
                "verbose_name_plural": "itens do pedido",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=100, verbose_name="ação")),
                ("entity_type", models.CharField(max_length=100, verbose_name="tipo da entidade")),
                ("entity_id", models.CharField(max_length=100, verbose_name="identificador da entidade")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="evidências")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to=settings.AUTH_USER_MODEL, verbose_name="operador")),
            ],
            options={
                "verbose_name": "evento de auditoria",
                "verbose_name_plural": "eventos de auditoria",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["entity_type", "entity_id"], name="orders_audi_entity__6c6488_idx"), models.Index(fields=["created_at"], name="orders_audi_created_d72da9_idx")],
            },
        ),
        migrations.CreateModel(
            name="MonthlyClosing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference_month", models.DateField(verbose_name="mês de referência")),
                ("order_count", models.PositiveIntegerField(default=0, verbose_name="total de pedidos")),
                ("item_count", models.PositiveIntegerField(default=0, verbose_name="total de itens")),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="valor total")),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("to_review", "A conferir"), ("validated", "Validado"), ("invoiced", "Faturado")], default="to_review", max_length=20, verbose_name="status")),
                ("message_snapshot", models.TextField(blank=True, verbose_name="mensagem do fechamento")),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                ("validated_at", models.DateTimeField(blank=True, null=True, verbose_name="validado em")),
                ("invoiced_at", models.DateTimeField(blank=True, null=True, verbose_name="faturado em")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="closings", to="orders.company", verbose_name="empresa")),
                ("generated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closings_generated", to=settings.AUTH_USER_MODEL, verbose_name="gerado por")),
            ],
            options={
                "verbose_name": "fechamento mensal",
                "verbose_name_plural": "fechamentos mensais",
                "ordering": ("-reference_month", "company__name"),
                "indexes": [models.Index(fields=["reference_month", "status"], name="orders_mont_referen_e39eef_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "reference_month"), name="unique_company_reference_month"), models.CheckConstraint(condition=models.Q(("total_amount__gte", 0)), name="closing_total_amount_non_negative")],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["delivery_date", "status"], name="orders_orde_deliver_238b9d_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["company", "order_date"], name="orders_orde_company_2eca5b_idx"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(condition=models.Q(("total_amount__gte", 0)), name="order_total_amount_non_negative"),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(fields=["order", "changed_at"], name="orders_orde_order_i_7978aa_idx"),
        ),
        migrations.AddConstraint(
            model_name="orderstatushistory",
            constraint=models.CheckConstraint(condition=models.Q(("from_status", models.F("to_status")), _negated=True), name="status_history_must_change"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(fields=("order", "product"), name="unique_product_per_order"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="order_item_quantity_gt_zero"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(condition=models.Q(("unit_price__gte", 0)), name="order_item_unit_price_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(condition=models.Q(("line_total__gte", 0)), name="order_item_line_total_non_negative"),
        ),
    ]
