# Generated by Django 5.2.16 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_company_is_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="document",
            field=models.CharField(
                blank=True,
                help_text="Opcional. Aceita pontuação e é armazenado somente com números.",
                max_length=18,
                verbose_name="CPF/CNPJ",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
        migrations.AddField(
            model_name="company",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("individual", "Pessoa física"),
                    ("company", "Pessoa jurídica"),
                ],
                default="company",
                max_length=20,
                verbose_name="natureza do cliente",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Identificador do cliente no sistema de origem.",
                max_length=100,
                verbose_name="identificador externo",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="Opcional. Aceita hífen e é armazenado somente com números.",
                max_length=10,
                verbose_name="CEP",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="source_system",
            field=models.CharField(
                blank=True,
                help_text="Preencher junto com o identificador externo.",
                max_length=50,
                verbose_name="sistema de origem",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF"),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=~models.Q(document=""),
                fields=("document",),
                name="unique_company_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=~models.Q(source_system="") & ~models.Q(external_id=""),
                fields=("source_system", "external_id"),
                name="unique_company_source_external",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(source_system="", external_id="")
                    | (~models.Q(source_system="") & ~models.Q(external_id=""))
                ),
                name="company_source_external_pair",
            ),
        ),
    ]
